export type QuotationStatus =
    | 'DRAFT'
    | 'PENDING_ASSIGNMENT'
    | 'PENDING_PROVIDER_BID'
    | 'PENDING_ADMIN_APPROVAL'
    | 'AWAITING_CLIENT_PAYMENT'
    | 'APPROVED'
    | 'PAID'
    | 'FULFILLED'
    | 'CANCELLED'
    | 'REJECTED';

export const QuotationStatus = {
    DRAFT: 'DRAFT',
    PENDING_ASSIGNMENT: 'PENDING_ASSIGNMENT',
    PENDING_PROVIDER_BID: 'PENDING_PROVIDER_BID',
    PENDING_ADMIN_APPROVAL: 'PENDING_ADMIN_APPROVAL',
    AWAITING_CLIENT_PAYMENT: 'AWAITING_CLIENT_PAYMENT',
    APPROVED: 'APPROVED',
    PAID: 'PAID',
    FULFILLED: 'FULFILLED',
    CANCELLED: 'CANCELLED',
    REJECTED: 'REJECTED'
} as const;
